#!/bin/bash
#
# Commit-msg hooks
# Check if commit message follows a specific structure

# Colour
RED="\e[31m"

# $1gets the first argument which is: .git/COMMIT_EDITMSG.
# .git/COMMIT_EDITMSG is used by git as the temporary file for the commit message.
INPUT_FILE=$1

#head -n1 will provide a trailing newline only if the input has one.
START_LINE=`head -n1 $INPUT_FILE`
echo $START_LINE
#Regex for update npm package
NPM_PATTERN="([0-9].)([0-9].)([0-9])$"

if ! [[ "$START_LINE" =~ $NPM_PATTERN ]]; then
  exit 0;
fi

#Regex for specific commit
PATTERN="IU-[0-9]{2,10}: [ A-Za-z0-9_.,-]*"

if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  printf "Invalid commit message.\nCommit name should use the following structure: <IU-ticketnumber>: <commit-message>\n"
  exit 1
fi
