#!/bin/bash
#
# Pre-push hook
# Check if branch name follows a specfic structure.

# Colour
RED="\e[31m"

# git rev-parse --abbrev-ref HEAD -> allow us to get the branch name
# grep -E is used for regular expression
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
printf "branch name -> ${BRANCH_NAME} \n"
if [ ${BRANCH_NAME} = "master" ] | [ ${BRANCH_NAME} = "main" ] ; then
  exit 0;
fi

# wc command counts characters
BRANCH_NAME_LENGTH=`git rev-parse --abbrev-ref HEAD | grep -E '^(feature|bug|refactor)\/IU-[0-9]{2,10}\/[A-Za-z0-9_-]*' | wc -c`

# if the branch name does not match with the regex it will output nothing so the wc -c will be equal to 0
if [ ${BRANCH_NAME_LENGTH} -eq 0 ] ; then
  printf "\n${RED}-Invalid Branch name. \n Branch name should use the following structure <feature/bug/refactor>/<IU-ticketnumber>/<context-name>.\n"
  exit 1
fi